# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/Repos/infpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/Repos/infpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Repos/infpp/CMakeFiles /storage/emulated/0/Repos/infpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Repos/infpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named n08

# Build rule for target.
n08: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 n08
.PHONY : n08

# fast build rule for target.
n08/fast:
	$(MAKE) -f CMakeFiles/n08.dir/build.make CMakeFiles/n08.dir/build
.PHONY : n08/fast

#=============================================================================
# Target rules for targets named n06

# Build rule for target.
n06: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 n06
.PHONY : n06

# fast build rule for target.
n06/fast:
	$(MAKE) -f CMakeFiles/n06.dir/build.make CMakeFiles/n06.dir/build
.PHONY : n06/fast

#=============================================================================
# Target rules for targets named n07

# Build rule for target.
n07: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 n07
.PHONY : n07

# fast build rule for target.
n07/fast:
	$(MAKE) -f CMakeFiles/n07.dir/build.make CMakeFiles/n07.dir/build
.PHONY : n07/fast

#=============================================================================
# Target rules for targets named n05

# Build rule for target.
n05: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 n05
.PHONY : n05

# fast build rule for target.
n05/fast:
	$(MAKE) -f CMakeFiles/n05.dir/build.make CMakeFiles/n05.dir/build
.PHONY : n05/fast

#=============================================================================
# Target rules for targets named n04

# Build rule for target.
n04: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 n04
.PHONY : n04

# fast build rule for target.
n04/fast:
	$(MAKE) -f CMakeFiles/n04.dir/build.make CMakeFiles/n04.dir/build
.PHONY : n04/fast

#=============================================================================
# Target rules for targets named n03

# Build rule for target.
n03: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 n03
.PHONY : n03

# fast build rule for target.
n03/fast:
	$(MAKE) -f CMakeFiles/n03.dir/build.make CMakeFiles/n03.dir/build
.PHONY : n03/fast

#=============================================================================
# Target rules for targets named n02

# Build rule for target.
n02: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 n02
.PHONY : n02

# fast build rule for target.
n02/fast:
	$(MAKE) -f CMakeFiles/n02.dir/build.make CMakeFiles/n02.dir/build
.PHONY : n02/fast

#=============================================================================
# Target rules for targets named n01

# Build rule for target.
n01: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 n01
.PHONY : n01

# fast build rule for target.
n01/fast:
	$(MAKE) -f CMakeFiles/n01.dir/build.make CMakeFiles/n01.dir/build
.PHONY : n01/fast

#=============================================================================
# Target rules for targets named vector_class

# Build rule for target.
vector_class: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vector_class
.PHONY : vector_class

# fast build rule for target.
vector_class/fast:
	$(MAKE) -f CMakeFiles/vector_class.dir/build.make CMakeFiles/vector_class.dir/build
.PHONY : vector_class/fast

memory/vector_class.o: memory/vector_class.cpp.o

.PHONY : memory/vector_class.o

# target to build an object file
memory/vector_class.cpp.o:
	$(MAKE) -f CMakeFiles/vector_class.dir/build.make CMakeFiles/vector_class.dir/memory/vector_class.cpp.o
.PHONY : memory/vector_class.cpp.o

memory/vector_class.i: memory/vector_class.cpp.i

.PHONY : memory/vector_class.i

# target to preprocess a source file
memory/vector_class.cpp.i:
	$(MAKE) -f CMakeFiles/vector_class.dir/build.make CMakeFiles/vector_class.dir/memory/vector_class.cpp.i
.PHONY : memory/vector_class.cpp.i

memory/vector_class.s: memory/vector_class.cpp.s

.PHONY : memory/vector_class.s

# target to generate assembly for a file
memory/vector_class.cpp.s:
	$(MAKE) -f CMakeFiles/vector_class.dir/build.make CMakeFiles/vector_class.dir/memory/vector_class.cpp.s
.PHONY : memory/vector_class.cpp.s

recursion/n01.o: recursion/n01.cpp.o

.PHONY : recursion/n01.o

# target to build an object file
recursion/n01.cpp.o:
	$(MAKE) -f CMakeFiles/n01.dir/build.make CMakeFiles/n01.dir/recursion/n01.cpp.o
.PHONY : recursion/n01.cpp.o

recursion/n01.i: recursion/n01.cpp.i

.PHONY : recursion/n01.i

# target to preprocess a source file
recursion/n01.cpp.i:
	$(MAKE) -f CMakeFiles/n01.dir/build.make CMakeFiles/n01.dir/recursion/n01.cpp.i
.PHONY : recursion/n01.cpp.i

recursion/n01.s: recursion/n01.cpp.s

.PHONY : recursion/n01.s

# target to generate assembly for a file
recursion/n01.cpp.s:
	$(MAKE) -f CMakeFiles/n01.dir/build.make CMakeFiles/n01.dir/recursion/n01.cpp.s
.PHONY : recursion/n01.cpp.s

recursion/n02.o: recursion/n02.cpp.o

.PHONY : recursion/n02.o

# target to build an object file
recursion/n02.cpp.o:
	$(MAKE) -f CMakeFiles/n02.dir/build.make CMakeFiles/n02.dir/recursion/n02.cpp.o
.PHONY : recursion/n02.cpp.o

recursion/n02.i: recursion/n02.cpp.i

.PHONY : recursion/n02.i

# target to preprocess a source file
recursion/n02.cpp.i:
	$(MAKE) -f CMakeFiles/n02.dir/build.make CMakeFiles/n02.dir/recursion/n02.cpp.i
.PHONY : recursion/n02.cpp.i

recursion/n02.s: recursion/n02.cpp.s

.PHONY : recursion/n02.s

# target to generate assembly for a file
recursion/n02.cpp.s:
	$(MAKE) -f CMakeFiles/n02.dir/build.make CMakeFiles/n02.dir/recursion/n02.cpp.s
.PHONY : recursion/n02.cpp.s

recursion/n03.o: recursion/n03.cpp.o

.PHONY : recursion/n03.o

# target to build an object file
recursion/n03.cpp.o:
	$(MAKE) -f CMakeFiles/n03.dir/build.make CMakeFiles/n03.dir/recursion/n03.cpp.o
.PHONY : recursion/n03.cpp.o

recursion/n03.i: recursion/n03.cpp.i

.PHONY : recursion/n03.i

# target to preprocess a source file
recursion/n03.cpp.i:
	$(MAKE) -f CMakeFiles/n03.dir/build.make CMakeFiles/n03.dir/recursion/n03.cpp.i
.PHONY : recursion/n03.cpp.i

recursion/n03.s: recursion/n03.cpp.s

.PHONY : recursion/n03.s

# target to generate assembly for a file
recursion/n03.cpp.s:
	$(MAKE) -f CMakeFiles/n03.dir/build.make CMakeFiles/n03.dir/recursion/n03.cpp.s
.PHONY : recursion/n03.cpp.s

recursion/n04.o: recursion/n04.cpp.o

.PHONY : recursion/n04.o

# target to build an object file
recursion/n04.cpp.o:
	$(MAKE) -f CMakeFiles/n04.dir/build.make CMakeFiles/n04.dir/recursion/n04.cpp.o
.PHONY : recursion/n04.cpp.o

recursion/n04.i: recursion/n04.cpp.i

.PHONY : recursion/n04.i

# target to preprocess a source file
recursion/n04.cpp.i:
	$(MAKE) -f CMakeFiles/n04.dir/build.make CMakeFiles/n04.dir/recursion/n04.cpp.i
.PHONY : recursion/n04.cpp.i

recursion/n04.s: recursion/n04.cpp.s

.PHONY : recursion/n04.s

# target to generate assembly for a file
recursion/n04.cpp.s:
	$(MAKE) -f CMakeFiles/n04.dir/build.make CMakeFiles/n04.dir/recursion/n04.cpp.s
.PHONY : recursion/n04.cpp.s

recursion/n05.o: recursion/n05.cpp.o

.PHONY : recursion/n05.o

# target to build an object file
recursion/n05.cpp.o:
	$(MAKE) -f CMakeFiles/n05.dir/build.make CMakeFiles/n05.dir/recursion/n05.cpp.o
.PHONY : recursion/n05.cpp.o

recursion/n05.i: recursion/n05.cpp.i

.PHONY : recursion/n05.i

# target to preprocess a source file
recursion/n05.cpp.i:
	$(MAKE) -f CMakeFiles/n05.dir/build.make CMakeFiles/n05.dir/recursion/n05.cpp.i
.PHONY : recursion/n05.cpp.i

recursion/n05.s: recursion/n05.cpp.s

.PHONY : recursion/n05.s

# target to generate assembly for a file
recursion/n05.cpp.s:
	$(MAKE) -f CMakeFiles/n05.dir/build.make CMakeFiles/n05.dir/recursion/n05.cpp.s
.PHONY : recursion/n05.cpp.s

recursion/n06.o: recursion/n06.cpp.o

.PHONY : recursion/n06.o

# target to build an object file
recursion/n06.cpp.o:
	$(MAKE) -f CMakeFiles/n06.dir/build.make CMakeFiles/n06.dir/recursion/n06.cpp.o
.PHONY : recursion/n06.cpp.o

recursion/n06.i: recursion/n06.cpp.i

.PHONY : recursion/n06.i

# target to preprocess a source file
recursion/n06.cpp.i:
	$(MAKE) -f CMakeFiles/n06.dir/build.make CMakeFiles/n06.dir/recursion/n06.cpp.i
.PHONY : recursion/n06.cpp.i

recursion/n06.s: recursion/n06.cpp.s

.PHONY : recursion/n06.s

# target to generate assembly for a file
recursion/n06.cpp.s:
	$(MAKE) -f CMakeFiles/n06.dir/build.make CMakeFiles/n06.dir/recursion/n06.cpp.s
.PHONY : recursion/n06.cpp.s

recursion/n07.o: recursion/n07.cpp.o

.PHONY : recursion/n07.o

# target to build an object file
recursion/n07.cpp.o:
	$(MAKE) -f CMakeFiles/n07.dir/build.make CMakeFiles/n07.dir/recursion/n07.cpp.o
.PHONY : recursion/n07.cpp.o

recursion/n07.i: recursion/n07.cpp.i

.PHONY : recursion/n07.i

# target to preprocess a source file
recursion/n07.cpp.i:
	$(MAKE) -f CMakeFiles/n07.dir/build.make CMakeFiles/n07.dir/recursion/n07.cpp.i
.PHONY : recursion/n07.cpp.i

recursion/n07.s: recursion/n07.cpp.s

.PHONY : recursion/n07.s

# target to generate assembly for a file
recursion/n07.cpp.s:
	$(MAKE) -f CMakeFiles/n07.dir/build.make CMakeFiles/n07.dir/recursion/n07.cpp.s
.PHONY : recursion/n07.cpp.s

recursion/n08.o: recursion/n08.cpp.o

.PHONY : recursion/n08.o

# target to build an object file
recursion/n08.cpp.o:
	$(MAKE) -f CMakeFiles/n08.dir/build.make CMakeFiles/n08.dir/recursion/n08.cpp.o
.PHONY : recursion/n08.cpp.o

recursion/n08.i: recursion/n08.cpp.i

.PHONY : recursion/n08.i

# target to preprocess a source file
recursion/n08.cpp.i:
	$(MAKE) -f CMakeFiles/n08.dir/build.make CMakeFiles/n08.dir/recursion/n08.cpp.i
.PHONY : recursion/n08.cpp.i

recursion/n08.s: recursion/n08.cpp.s

.PHONY : recursion/n08.s

# target to generate assembly for a file
recursion/n08.cpp.s:
	$(MAKE) -f CMakeFiles/n08.dir/build.make CMakeFiles/n08.dir/recursion/n08.cpp.s
.PHONY : recursion/n08.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... n08"
	@echo "... n06"
	@echo "... n07"
	@echo "... n05"
	@echo "... n04"
	@echo "... n03"
	@echo "... n02"
	@echo "... edit_cache"
	@echo "... n01"
	@echo "... vector_class"
	@echo "... memory/vector_class.o"
	@echo "... memory/vector_class.i"
	@echo "... memory/vector_class.s"
	@echo "... recursion/n01.o"
	@echo "... recursion/n01.i"
	@echo "... recursion/n01.s"
	@echo "... recursion/n02.o"
	@echo "... recursion/n02.i"
	@echo "... recursion/n02.s"
	@echo "... recursion/n03.o"
	@echo "... recursion/n03.i"
	@echo "... recursion/n03.s"
	@echo "... recursion/n04.o"
	@echo "... recursion/n04.i"
	@echo "... recursion/n04.s"
	@echo "... recursion/n05.o"
	@echo "... recursion/n05.i"
	@echo "... recursion/n05.s"
	@echo "... recursion/n06.o"
	@echo "... recursion/n06.i"
	@echo "... recursion/n06.s"
	@echo "... recursion/n07.o"
	@echo "... recursion/n07.i"
	@echo "... recursion/n07.s"
	@echo "... recursion/n08.o"
	@echo "... recursion/n08.i"
	@echo "... recursion/n08.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

